sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - goodluckhf@yandex.ru
    on_success: never
    on_failure: always

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - npm i -g npm@6

stages:
  - lint
  - test
  - name: release
    if: branch = master
jobs:
  include:
    - stage: lint
      node_js:
        - '10'
      before_script:
        - npm prune
      script:
        - npm run lint
        - npm run build
    - stage: test
      node_js:
        - '10'
        - '9'
        - '8'
      before_script:
        - npm prune
      script:
        - npm run test:cov
      after_success:
        - npm run report-coverage
    - stage: release
      node_js: '8'
      script:
        - npm run build
        - npm run semantic-release
